n1=input('Digite algo:')
print(type(n1))
print('isalnum {}'.format(n1.isalnum()))
print('Alfabético?{} Captalizado?{} Mínusculas?{} Maiusculas?{} Espaços?{}'.format(n1.isalpha(), n1.istitle(), n1.isupper(), n1.islower(), n1.isspace()))
print(n1.isalpha())
print(n1.isascii())
print(n1.isdigit())
print(n1.islower())
print(n1.isdecimal())
print(n1.isidentifier())
print(n1.isprintable())
print(n1.isnumeric())
print(n1.isspace())
print(n1.istitle())
print(n1.isupper())
